// Generated: country (ISO-3166-1 alpha-2) -> 6-continent code + UN/mledoze subregion.
// Source: github.com/mledoze/countries. Regenerate with scripts/generate_continents.py.

export const CONTINENTS = [
  { code: "AF", name: "Africa" },
  { code: "AS", name: "Asia" },
  { code: "EU", name: "Europe" },
  { code: "NA", name: "North America" },
  { code: "OC", name: "Oceania" },
  { code: "SA", name: "South America" },
] as const;

export type ContinentCode = (typeof CONTINENTS)[number]["code"];

export const COUNTRY_GEO: Record<string, { continent: ContinentCode; subregion: string }> = {
  AD: { continent: "EU", subregion: "Southern Europe" },
  AE: { continent: "AS", subregion: "Western Asia" },
  AF: { continent: "AS", subregion: "Southern Asia" },
  AG: { continent: "NA", subregion: "Caribbean" },
  AI: { continent: "NA", subregion: "Caribbean" },
  AL: { continent: "EU", subregion: "Southeast Europe" },
  AM: { continent: "AS", subregion: "Western Asia" },
  AO: { continent: "AF", subregion: "Middle Africa" },
  AR: { continent: "SA", subregion: "South America" },
  AS: { continent: "OC", subregion: "Polynesia" },
  AT: { continent: "EU", subregion: "Central Europe" },
  AU: { continent: "OC", subregion: "Australia & NZ" },
  AW: { continent: "NA", subregion: "Caribbean" },
  AX: { continent: "EU", subregion: "Northern Europe" },
  AZ: { continent: "AS", subregion: "Western Asia" },
  BA: { continent: "EU", subregion: "Southeast Europe" },
  BB: { continent: "NA", subregion: "Caribbean" },
  BD: { continent: "AS", subregion: "Southern Asia" },
  BE: { continent: "EU", subregion: "Western Europe" },
  BF: { continent: "AF", subregion: "Western Africa" },
  BG: { continent: "EU", subregion: "Southeast Europe" },
  BH: { continent: "AS", subregion: "Western Asia" },
  BI: { continent: "AF", subregion: "Eastern Africa" },
  BJ: { continent: "AF", subregion: "Western Africa" },
  BL: { continent: "NA", subregion: "Caribbean" },
  BM: { continent: "NA", subregion: "North America" },
  BN: { continent: "AS", subregion: "Southeast Asia" },
  BO: { continent: "SA", subregion: "South America" },
  BQ: { continent: "NA", subregion: "Caribbean" },
  BR: { continent: "SA", subregion: "South America" },
  BS: { continent: "NA", subregion: "Caribbean" },
  BT: { continent: "AS", subregion: "Southern Asia" },
  BW: { continent: "AF", subregion: "Southern Africa" },
  BY: { continent: "EU", subregion: "Eastern Europe" },
  BZ: { continent: "NA", subregion: "Central America" },
  CA: { continent: "NA", subregion: "North America" },
  CC: { continent: "OC", subregion: "Australia & NZ" },
  CD: { continent: "AF", subregion: "Middle Africa" },
  CF: { continent: "AF", subregion: "Middle Africa" },
  CG: { continent: "AF", subregion: "Middle Africa" },
  CH: { continent: "EU", subregion: "Western Europe" },
  CI: { continent: "AF", subregion: "Western Africa" },
  CK: { continent: "OC", subregion: "Polynesia" },
  CL: { continent: "SA", subregion: "South America" },
  CM: { continent: "AF", subregion: "Middle Africa" },
  CN: { continent: "AS", subregion: "Eastern Asia" },
  CO: { continent: "SA", subregion: "South America" },
  CR: { continent: "NA", subregion: "Central America" },
  CU: { continent: "NA", subregion: "Caribbean" },
  CV: { continent: "AF", subregion: "Western Africa" },
  CW: { continent: "NA", subregion: "Caribbean" },
  CX: { continent: "OC", subregion: "Australia & NZ" },
  CY: { continent: "EU", subregion: "Southern Europe" },
  CZ: { continent: "EU", subregion: "Central Europe" },
  DE: { continent: "EU", subregion: "Western Europe" },
  DJ: { continent: "AF", subregion: "Eastern Africa" },
  DK: { continent: "EU", subregion: "Northern Europe" },
  DM: { continent: "NA", subregion: "Caribbean" },
  DO: { continent: "NA", subregion: "Caribbean" },
  DZ: { continent: "AF", subregion: "Northern Africa" },
  EC: { continent: "SA", subregion: "South America" },
  EE: { continent: "EU", subregion: "Northern Europe" },
  EG: { continent: "AF", subregion: "Northern Africa" },
  EH: { continent: "AF", subregion: "Northern Africa" },
  ER: { continent: "AF", subregion: "Eastern Africa" },
  ES: { continent: "EU", subregion: "Southern Europe" },
  ET: { continent: "AF", subregion: "Eastern Africa" },
  FI: { continent: "EU", subregion: "Northern Europe" },
  FJ: { continent: "OC", subregion: "Melanesia" },
  FK: { continent: "SA", subregion: "South America" },
  FM: { continent: "OC", subregion: "Micronesia" },
  FO: { continent: "EU", subregion: "Northern Europe" },
  FR: { continent: "EU", subregion: "Western Europe" },
  GA: { continent: "AF", subregion: "Middle Africa" },
  GB: { continent: "EU", subregion: "Northern Europe" },
  GD: { continent: "NA", subregion: "Caribbean" },
  GE: { continent: "AS", subregion: "Western Asia" },
  GF: { continent: "SA", subregion: "South America" },
  GG: { continent: "EU", subregion: "Northern Europe" },
  GH: { continent: "AF", subregion: "Western Africa" },
  GI: { continent: "EU", subregion: "Southern Europe" },
  GL: { continent: "NA", subregion: "North America" },
  GM: { continent: "AF", subregion: "Western Africa" },
  GN: { continent: "AF", subregion: "Western Africa" },
  GP: { continent: "NA", subregion: "Caribbean" },
  GQ: { continent: "AF", subregion: "Middle Africa" },
  GR: { continent: "EU", subregion: "Southern Europe" },
  GT: { continent: "NA", subregion: "Central America" },
  GU: { continent: "OC", subregion: "Micronesia" },
  GW: { continent: "AF", subregion: "Western Africa" },
  GY: { continent: "SA", subregion: "South America" },
  HK: { continent: "AS", subregion: "Eastern Asia" },
  HN: { continent: "NA", subregion: "Central America" },
  HR: { continent: "EU", subregion: "Southeast Europe" },
  HT: { continent: "NA", subregion: "Caribbean" },
  HU: { continent: "EU", subregion: "Central Europe" },
  ID: { continent: "AS", subregion: "Southeast Asia" },
  IE: { continent: "EU", subregion: "Northern Europe" },
  IL: { continent: "AS", subregion: "Western Asia" },
  IM: { continent: "EU", subregion: "Northern Europe" },
  IN: { continent: "AS", subregion: "Southern Asia" },
  IO: { continent: "AF", subregion: "Eastern Africa" },
  IQ: { continent: "AS", subregion: "Western Asia" },
  IR: { continent: "AS", subregion: "Southern Asia" },
  IS: { continent: "EU", subregion: "Northern Europe" },
  IT: { continent: "EU", subregion: "Southern Europe" },
  JE: { continent: "EU", subregion: "Northern Europe" },
  JM: { continent: "NA", subregion: "Caribbean" },
  JO: { continent: "AS", subregion: "Western Asia" },
  JP: { continent: "AS", subregion: "Eastern Asia" },
  KE: { continent: "AF", subregion: "Eastern Africa" },
  KG: { continent: "AS", subregion: "Central Asia" },
  KH: { continent: "AS", subregion: "Southeast Asia" },
  KI: { continent: "OC", subregion: "Micronesia" },
  KM: { continent: "AF", subregion: "Eastern Africa" },
  KN: { continent: "NA", subregion: "Caribbean" },
  KP: { continent: "AS", subregion: "Eastern Asia" },
  KR: { continent: "AS", subregion: "Eastern Asia" },
  KW: { continent: "AS", subregion: "Western Asia" },
  KY: { continent: "NA", subregion: "Caribbean" },
  KZ: { continent: "AS", subregion: "Central Asia" },
  LA: { continent: "AS", subregion: "Southeast Asia" },
  LB: { continent: "AS", subregion: "Western Asia" },
  LC: { continent: "NA", subregion: "Caribbean" },
  LI: { continent: "EU", subregion: "Western Europe" },
  LK: { continent: "AS", subregion: "Southern Asia" },
  LR: { continent: "AF", subregion: "Western Africa" },
  LS: { continent: "AF", subregion: "Southern Africa" },
  LT: { continent: "EU", subregion: "Northern Europe" },
  LU: { continent: "EU", subregion: "Western Europe" },
  LV: { continent: "EU", subregion: "Northern Europe" },
  LY: { continent: "AF", subregion: "Northern Africa" },
  MA: { continent: "AF", subregion: "Northern Africa" },
  MC: { continent: "EU", subregion: "Western Europe" },
  MD: { continent: "EU", subregion: "Eastern Europe" },
  ME: { continent: "EU", subregion: "Southeast Europe" },
  MF: { continent: "NA", subregion: "Caribbean" },
  MG: { continent: "AF", subregion: "Eastern Africa" },
  MH: { continent: "OC", subregion: "Micronesia" },
  MK: { continent: "EU", subregion: "Southeast Europe" },
  ML: { continent: "AF", subregion: "Western Africa" },
  MM: { continent: "AS", subregion: "Southeast Asia" },
  MN: { continent: "AS", subregion: "Eastern Asia" },
  MO: { continent: "AS", subregion: "Eastern Asia" },
  MP: { continent: "OC", subregion: "Micronesia" },
  MQ: { continent: "NA", subregion: "Caribbean" },
  MR: { continent: "AF", subregion: "Western Africa" },
  MS: { continent: "NA", subregion: "Caribbean" },
  MT: { continent: "EU", subregion: "Southern Europe" },
  MU: { continent: "AF", subregion: "Eastern Africa" },
  MV: { continent: "AS", subregion: "Southern Asia" },
  MW: { continent: "AF", subregion: "Eastern Africa" },
  MX: { continent: "NA", subregion: "North America" },
  MY: { continent: "AS", subregion: "Southeast Asia" },
  MZ: { continent: "AF", subregion: "Eastern Africa" },
  NA: { continent: "AF", subregion: "Southern Africa" },
  NC: { continent: "OC", subregion: "Melanesia" },
  NE: { continent: "AF", subregion: "Western Africa" },
  NF: { continent: "OC", subregion: "Australia & NZ" },
  NG: { continent: "AF", subregion: "Western Africa" },
  NI: { continent: "NA", subregion: "Central America" },
  NL: { continent: "EU", subregion: "Western Europe" },
  NO: { continent: "EU", subregion: "Northern Europe" },
  NP: { continent: "AS", subregion: "Southern Asia" },
  NR: { continent: "OC", subregion: "Micronesia" },
  NU: { continent: "OC", subregion: "Polynesia" },
  NZ: { continent: "OC", subregion: "Australia & NZ" },
  OM: { continent: "AS", subregion: "Western Asia" },
  PA: { continent: "NA", subregion: "Central America" },
  PE: { continent: "SA", subregion: "South America" },
  PF: { continent: "OC", subregion: "Polynesia" },
  PG: { continent: "OC", subregion: "Melanesia" },
  PH: { continent: "AS", subregion: "Southeast Asia" },
  PK: { continent: "AS", subregion: "Southern Asia" },
  PL: { continent: "EU", subregion: "Central Europe" },
  PM: { continent: "NA", subregion: "North America" },
  PN: { continent: "OC", subregion: "Polynesia" },
  PR: { continent: "NA", subregion: "Caribbean" },
  PS: { continent: "AS", subregion: "Western Asia" },
  PT: { continent: "EU", subregion: "Southern Europe" },
  PW: { continent: "OC", subregion: "Micronesia" },
  PY: { continent: "SA", subregion: "South America" },
  QA: { continent: "AS", subregion: "Western Asia" },
  RE: { continent: "AF", subregion: "Eastern Africa" },
  RO: { continent: "EU", subregion: "Southeast Europe" },
  RS: { continent: "EU", subregion: "Southeast Europe" },
  RU: { continent: "EU", subregion: "Eastern Europe" },
  RW: { continent: "AF", subregion: "Eastern Africa" },
  SA: { continent: "AS", subregion: "Western Asia" },
  SB: { continent: "OC", subregion: "Melanesia" },
  SC: { continent: "AF", subregion: "Eastern Africa" },
  SD: { continent: "AF", subregion: "Northern Africa" },
  SE: { continent: "EU", subregion: "Northern Europe" },
  SG: { continent: "AS", subregion: "Southeast Asia" },
  SH: { continent: "AF", subregion: "Western Africa" },
  SI: { continent: "EU", subregion: "Central Europe" },
  SJ: { continent: "EU", subregion: "Northern Europe" },
  SK: { continent: "EU", subregion: "Central Europe" },
  SL: { continent: "AF", subregion: "Western Africa" },
  SM: { continent: "EU", subregion: "Southern Europe" },
  SN: { continent: "AF", subregion: "Western Africa" },
  SO: { continent: "AF", subregion: "Eastern Africa" },
  SR: { continent: "SA", subregion: "South America" },
  SS: { continent: "AF", subregion: "Middle Africa" },
  ST: { continent: "AF", subregion: "Middle Africa" },
  SV: { continent: "NA", subregion: "Central America" },
  SX: { continent: "NA", subregion: "Caribbean" },
  SY: { continent: "AS", subregion: "Western Asia" },
  SZ: { continent: "AF", subregion: "Southern Africa" },
  TC: { continent: "NA", subregion: "Caribbean" },
  TD: { continent: "AF", subregion: "Middle Africa" },
  TG: { continent: "AF", subregion: "Western Africa" },
  TH: { continent: "AS", subregion: "Southeast Asia" },
  TJ: { continent: "AS", subregion: "Central Asia" },
  TK: { continent: "OC", subregion: "Polynesia" },
  TL: { continent: "AS", subregion: "Southeast Asia" },
  TM: { continent: "AS", subregion: "Central Asia" },
  TN: { continent: "AF", subregion: "Northern Africa" },
  TO: { continent: "OC", subregion: "Polynesia" },
  TR: { continent: "AS", subregion: "Western Asia" },
  TT: { continent: "NA", subregion: "Caribbean" },
  TV: { continent: "OC", subregion: "Polynesia" },
  TW: { continent: "AS", subregion: "Eastern Asia" },
  TZ: { continent: "AF", subregion: "Eastern Africa" },
  UA: { continent: "EU", subregion: "Eastern Europe" },
  UG: { continent: "AF", subregion: "Eastern Africa" },
  UM: { continent: "NA", subregion: "North America" },
  US: { continent: "NA", subregion: "North America" },
  UY: { continent: "SA", subregion: "South America" },
  UZ: { continent: "AS", subregion: "Central Asia" },
  VA: { continent: "EU", subregion: "Southern Europe" },
  VC: { continent: "NA", subregion: "Caribbean" },
  VE: { continent: "SA", subregion: "South America" },
  VG: { continent: "NA", subregion: "Caribbean" },
  VI: { continent: "NA", subregion: "Caribbean" },
  VN: { continent: "AS", subregion: "Southeast Asia" },
  VU: { continent: "OC", subregion: "Melanesia" },
  WF: { continent: "OC", subregion: "Polynesia" },
  WS: { continent: "OC", subregion: "Polynesia" },
  XK: { continent: "EU", subregion: "Southeast Europe" },
  YE: { continent: "AS", subregion: "Western Asia" },
  YT: { continent: "AF", subregion: "Eastern Africa" },
  ZA: { continent: "AF", subregion: "Southern Africa" },
  ZM: { continent: "AF", subregion: "Eastern Africa" },
  ZW: { continent: "AF", subregion: "Eastern Africa" },
};
