#!/usr/bin/env python3
"""Generate src/lib/continents.ts: ISO-3166-1 alpha-2 -> 6-continent code + subregion.
Source: github.com/mledoze/countries (region -> our 6 continents; subregion as-is)."""
import json, urllib.request, os
md = json.load(urllib.request.urlopen("https://raw.githubusercontent.com/mledoze/countries/master/countries.json"))
def cont(region, sub):
    return {"Africa":"AF","Asia":"AS","Europe":"EU","Oceania":"OC"}.get(region) or ("SA" if region=="Americas" and sub=="South America" else "NA" if region=="Americas" else None)
RENAME = {"Northern America":"North America","South-Eastern Asia":"Southeast Asia","Australia and New Zealand":"Australia & NZ"}
geo = {}
for c in md:
    iso2 = c["cca2"]; sub = c.get("subregion","") or c.get("region","")
    k = cont(c.get("region",""), c.get("subregion",""))
    # sovereign states only — drop dependencies/territories (independent === false)
    if k and iso2 and c.get("independent") is not False:
        geo[iso2] = {"continent": k, "subregion": RENAME.get(sub, sub)}
out = ['// Generated by scripts/generate_continents.py — country -> 6-continent + subregion.',
       '// Source: github.com/mledoze/countries','',
       'export const CONTINENTS = [',
       *[f'  {{ code: "{c}", name: "{n}" }},' for c,n in [("AF","Africa"),("AS","Asia"),("EU","Europe"),("NA","North America"),("OC","Oceania"),("SA","South America")]],
       '] as const;','','export type ContinentCode = (typeof CONTINENTS)[number]["code"];','',
       'export const COUNTRY_GEO: Record<string, { continent: ContinentCode; subregion: string }> = {']
for iso2 in sorted(geo):
    out.append(f'  {iso2}: {{ continent: "{geo[iso2]["continent"]}", subregion: "{geo[iso2]["subregion"]}" }},')
out.append("};")
open(os.path.join(os.path.dirname(__file__),"..","src","lib","continents.ts"),"w").write("\n".join(out)+"\n")
print("wrote src/lib/continents.ts:", len(geo), "countries")
