#!/usr/bin/env python3
"""Generate src/lib/continents.ts: ISO-3166-1 alpha-2 -> 6-continent code + subregion.

Sovereign states (mledoze independent !== false) plus Taiwan & Palestine (travelers
treat them as distinct destinations). Every dependency/territory is mapped to its parent
sovereign via TERRITORY_PARENT, so a visit there counts as the parent country.
Source: github.com/mledoze/countries."""
import json, urllib.request, os
md = json.load(urllib.request.urlopen("https://raw.githubusercontent.com/mledoze/countries/master/countries.json"))
def cont(region, sub):
    return {"Africa":"AF","Asia":"AS","Europe":"EU","Oceania":"OC"}.get(region) or ("SA" if region=="Americas" and sub=="South America" else "NA" if region=="Americas" else None)
RENAME = {"Northern America":"North America","South-Eastern Asia":"Southeast Asia","Australia and New Zealand":"Australia & NZ"}

# Dependency / territory -> parent sovereign (ISO-2). A visit to the territory counts as
# the parent. Taiwan (TW) and Palestine (PS) are intentionally NOT here — kept standalone.
TERRITORY_PARENT = {
    # United Kingdom
    "AI":"GB","BM":"GB","FK":"GB","GG":"GB","GI":"GB","IM":"GB","IO":"GB","JE":"GB",
    "KY":"GB","MS":"GB","PN":"GB","SH":"GB","TC":"GB","VG":"GB",
    # France
    "BL":"FR","GF":"FR","GP":"FR","MF":"FR","MQ":"FR","NC":"FR","PF":"FR","PM":"FR",
    "RE":"FR","WF":"FR","YT":"FR",
    # United States
    "AS":"US","GU":"US","MP":"US","PR":"US","UM":"US","VI":"US",
    # Netherlands
    "AW":"NL","BQ":"NL","CW":"NL","SX":"NL",
    # Nordics
    "FO":"DK","GL":"DK","AX":"FI","SJ":"NO",
    # New Zealand
    "CK":"NZ","NU":"NZ","TK":"NZ",
    # Australia
    "CC":"AU","CX":"AU","NF":"AU",
    # China
    "HK":"CN","MO":"CN",
    # Morocco
    "EH":"MA",
}

# Standalone (kept as their own country even though mledoze marks them non-independent).
STANDALONE = {"TW":("AS","Eastern Asia"), "PS":("AS","Western Asia")}

geo = {}
for c in md:
    iso2 = c["cca2"]; sub = c.get("subregion","") or c.get("region","")
    k = cont(c.get("region",""), c.get("subregion",""))
    if k and iso2 and c.get("independent") is not False:
        geo[iso2] = {"continent": k, "subregion": RENAME.get(sub, sub)}
for iso2,(k,sub) in STANDALONE.items():
    geo[iso2] = {"continent": k, "subregion": sub}

out = ['// Generated by scripts/generate_continents.py — country -> 6-continent + subregion.',
       '// Sovereign states (+ Taiwan, Palestine); dependencies map to a parent via TERRITORY_PARENT.',
       '// Source: github.com/mledoze/countries','',
       'export const CONTINENTS = [',
       *[f'  {{ code: "{c}", name: "{n}" }},' for c,n in [("AF","Africa"),("AS","Asia"),("EU","Europe"),("NA","North America"),("OC","Oceania"),("SA","South America")]],
       '] as const;','','export type ContinentCode = (typeof CONTINENTS)[number]["code"];','',
       'export const COUNTRY_GEO: Record<string, { continent: ContinentCode; subregion: string }> = {']
for iso2 in sorted(geo):
    out.append(f'  {iso2}: {{ continent: "{geo[iso2]["continent"]}", subregion: "{geo[iso2]["subregion"]}" }},')
out.append("};")
out += ['','// Dependency/territory ISO-2 -> parent sovereign ISO-2 (resolve before counting).',
        'export const TERRITORY_PARENT: Record<string, string> = {']
for iso2 in sorted(TERRITORY_PARENT):
    out.append(f'  {iso2}: "{TERRITORY_PARENT[iso2]}",')
out.append("};")
out += ['','// Resolve a country/territory code to the sovereign country it counts toward.',
        'export const sovereignOf = (iso: string | null | undefined): string | null =>',
        '  iso ? TERRITORY_PARENT[iso] ?? iso : null;']
open(os.path.join(os.path.dirname(__file__),"..","src","lib","continents.ts"),"w").write("\n".join(out)+"\n")
print("wrote src/lib/continents.ts:", len(geo), "countries +", len(TERRITORY_PARENT), "territories")
